# Define am_alsa using the pcm audio manager alsa plugin
pcm.am_alsa {
  type pcm_audio_manager
}

# Define 'plug' plugin which might be used as a fallback (optional)
pcm.plug {
  type plug
  slave {
    pcm "hw:0,0"
  }
}

# The following lines define the pcm audio manager as the default device
pcm.!default {
  type am_alsa
}
